s:1473:"<b>Failed tests</b><br />Test 1: Teste 1
<br />Test 2: Teste 2
<br />Test 3: Teste 3
<br /><b>Test 1: Teste 1 </b><br />Incorrect program result
<br /> --- Input ---
<br /><pre><i> 144
12
</i></pre>
<br /> --- Program output ---
<br /><pre><i>digite o valor de n:digite o valor de m:Traceback (most recent call last):
  File "exercicio24.py", line 7, in &lt;module&gt;
    mdc=a
NameError: name 'a' is not defined
</i></pre>
<br /> --- Expected output (text)---
<br /><pre><i> '12'
</i></pre>
<br /><b>Test 2: Teste 2 </b><br />Incorrect program result
<br /> --- Input ---
<br /><pre><i> 982
16
</i></pre>
<br /> --- Program output ---
<br /><pre><i>digite o valor de n:digite o valor de m:Traceback (most recent call last):
  File "exercicio24.py", line 7, in &lt;module&gt;
    mdc=a
NameError: name 'a' is not defined
</i></pre>
<br /> --- Expected output (text)---
<br /><pre><i> '2'
</i></pre>
<br /><b>Test 3: Teste 3 </b><br />Incorrect program result
<br /> --- Input ---
<br /><pre><i> 980
20
</i></pre>
<br /> --- Program output ---
<br /><pre><i>digite o valor de n:digite o valor de m:Traceback (most recent call last):
  File "exercicio24.py", line 7, in &lt;module&gt;
    mdc=a
NameError: name 'a' is not defined
</i></pre>
<br /> --- Expected output (text)---
<br /><pre><i> '20'
</i></pre>
<br /><b>Summary of tests</b><br /><pre><i>+------------------------------+
|  3 tests run/ 0 tests passed |
+------------------------------+
</i></pre>
<br /><br />";