s:539:"<b>Test 1: Test 1 </b><br />Incorrect program result
<br /> --- Input ---
<br /><pre><i> 1
2
3
</i></pre>
<br /> --- Program output ---
<br /><pre><i>Traceback (most recent call last):
  File "ex1.py", line 8, in &lt;module&gt;
    if (a&gt;=b and a&gt;=c):
NameError: name 'a' is not defined
</i></pre>
<br /> --- Expected output (numbers)---
<br /><pre><i>3.00
</i></pre>
<br /><b>Summary of tests</b><br /><pre><i>+------------------------------+
|  2 tests run/ 1  test passed |
+------------------------------+
</i></pre>
<br /><br />";