s:983:"<b>Failed tests</b><br />Test 1: Teste 1
<br />Test 4: Teste 4
<br /><b>Test 1: Teste 1 </b><br />Incorrect program result
<br /> --- Input ---
<br /><pre><i>42
</i></pre>
<br /> --- Program output ---
<br /><pre><i>NAO SEI
Traceback (most recent call last):
  File "exe11.py", line 8, in &lt;module&gt;
    n=int(input())
EOFError: EOF when reading a line
</i></pre>
<br /> --- Expected output (text)---
<br /><pre><i>'NAO SEI'
</i></pre>
<br /><b>Test 4: Teste 4 </b><br />Incorrect program result
<br /> --- Input ---
<br /><pre><i>123
</i></pre>
<br /> --- Program output ---
<br /><pre><i>NAO SEI
Traceback (most recent call last):
  File "exe11.py", line 8, in &lt;module&gt;
    n=int(input())
EOFError: EOF when reading a line
</i></pre>
<br /> --- Expected output (text)---
<br /><pre><i>'NAO SEI'
</i></pre>
<br /><b>Summary of tests</b><br /><pre><i>+------------------------------+
|  4 tests run/ 2 tests passed |
+------------------------------+
</i></pre>
<br /><br />";