-Failed tests
Test 1: teste1
Test 2: teste2
-Test 1: teste1 (-15.000)
Incorrect program result
 --- Input ---
>3
>20000
>0
>20000
>33333

 --- Program output ---
>N:M:digite a:Traceback (most recent call last):
>  File "Maratona.py", line 7, in <module>
>    cont=o
>NameError: name 'o' is not defined

 --- Expected output (text)---
>'S'

-Test 2: teste2 (-15.000)
Incorrect program result
 --- Input ---
>8
>6000
>0
>6000
>12000
>18000
>24000
>32000
>37000
>45000

 --- Program output ---
>N:M:digite a:Traceback (most recent call last):
>  File "Maratona.py", line 7, in <module>
>    cont=o
>NameError: name 'o' is not defined

 --- Expected output (text)---
>'N'

-Summary of tests
>+------------------------------+
>|  2 tests run/ 0 tests passed |
>+------------------------------+

