s:569:"<b>Test 1: Teste 1 </b><br />Incorrect program result
<br /> --- Input ---
<br /><pre><i> 123.56
</i></pre>
<br /> --- Program output ---
<br /><pre><i>digite o valor que deseja sacar:Traceback (most recent call last):
  File "atm.py", line 6, in &lt;module&gt;
    n2 =(v2%20)//10
NameError: name 'v2' is not defined
</i></pre>
<br /> --- Expected output (numbers)---
<br /><pre><i>6
0
0
1
1
</i></pre>
<br /><b>Summary of tests</b><br /><pre><i>+------------------------------+
|  1  test run/ 0 tests passed |
+------------------------------+
</i></pre>
<br /><br />";