-Test 1: Teste 1 (-10.000)
Incorrect program result
 --- Input ---
> 123.56

 --- Program output ---
>xTraceback (most recent call last):
>  File "atm.py", line 7, in <module>
>    n1=(x//20)
>NameError: name 'x' is not defined

 --- Expected output (numbers)---
>6
>0
>0
>1
>1

-Summary of tests
>+------------------------------+
>|  1  test run/ 0 tests passed |
>+------------------------------+

