-Failed tests
Test 2: Teste 2
Test 3: Teste 3
-Test 2: Teste 2 (-10.000)
Incorrect program result
 --- Input ---
> 7
>1
>2
>1
>2
>1
>2
>1

 --- Program output ---
>Digite a quantidade de elementos da lista: Digite a: Digite a: Digite a: Digite a: Digite a: Digite a: Digite a: S

 --- Expected output (text)---
> 'N'

-Test 3: Teste 3 (-10.000)
Incorrect program result
 --- Input ---
> 4
>10
>9
>7
>4

 --- Program output ---
>Digite a quantidade de elementos da lista: Digite a: Digite a: Digite a: Digite a: Traceback (most recent call last):
>  File "pico.py", line 45, in <module>
>    if pico(a):
>  File "pico.py", line 7, in pico
>    for i in range(0, (n/2)-1, 1):
>TypeError: range() integer end argument expected, got float.

 --- Expected output (text)---
> 'N'

-Summary of tests
>+------------------------------+
>|  4 tests run/ 2 tests passed |
>+------------------------------+

